In [1]:
import pandas as pd
import numpy as np

# <center>1. Data Collection </center>

</b> - Snapshot at 12.07.2022 17:00 CEST

## <u> BTC</u>
- https://bitinfocharts.com/top-100-richest-bitcoin-addresses.html

In [2]:
current_supply_BTC = 19091931.00

df = pd.read_csv("Data/1. Raw/F100BTC.csv", sep=';', index_col=0, encoding = "ISO-8859-1")
df = df[df['Balance'].notna()]
df = df.drop("Bal", axis=1)
df['Balance'] = df['Balance'].str.replace(',','').str.replace('B','').astype('int32')

In [3]:
df.head(12)

                                                Address  Balance     Label
1.0                  34xp4vRoCGJym3xR7yCVPFHoCNxv4Twseo   252597  Exchange
2.0   bc1qgdjqv0av3q56jvd82tkdjpy7gdp9ut8tlqmgrpmv24...   168010  Exchange
3.0                  1P5ZEDWTKTFGxQjZphgWPQUpe554WKDfHQ   132324       NaN
4.0                  3LYJfcfHPXYJreMsASk2jkn69LWEYKzexb   125351  Exchange
5.0                  3M219KR5vEneNb47ewrPfWyb5jQ2DjxRP6   101266  Exchange
6.0          bc1qazcm763858nkj2dj986etajv6wquslv8uxwczt    94643       NaN
7.0                  37XuVSEpWW4trkfmvWzegTHQt7BdktSKUs    94505       NaN
8.0                  1FeexV6bAHb8ybZjqQMjJrcCrHGW9sb6uF    79957       NaN
9.0          bc1qa5wkgaew2dkv56kfvj49j0av5nml45x9ek9hz6    69370       NaN
10.0  bc1qd4ysezhmypwty5dnw7c8nqy5h5nxg0xqsvaefd0qn5...    64300       NaN
11.0          3Kzh9qAqVWQhEsfQz7zEQL1EuSx5tyNLNSÊ2-of-3    61419  Exchange
12.0                 1LdRcdxfbSnmCYYNdeYpUnztiYzVfBEQeC    53880       NaN

In [4]:
df.to_csv("Data/2. Cleaned/FinalBTC.csv")

## <u> DOGE</u>
- https://bitinfocharts.com/top-100-richest-dogecoin-addresses.html

In [5]:
current_supply_DOGE = 132670000000

dfD = pd.read_csv("Data/1. Raw/F100DOGE.csv", sep=';', index_col=0, encoding = "ISO-8859-1")
dfD = dfD[dfD['Balance'].notna()]
dfD = dfD.drop("Bal", axis=1)
dfD = dfD.drop("B", axis=1)

In [6]:
dfD.head(12)

                                 Address       Balance     Label
ï»¿
1.0   DBs4WcRE7eysKwRxHNX88XZVCQ9M6QSUSz  2.916194e+10  Exchange
2.0   DE5opaXjFgDhFBqL6tBDxTAQ56zkX6EToX  7.247474e+09  Exchange
3.0   DRSqEwcnJX3GZWH9Twtwk8D5ewqdJzi13k  6.850847e+09       NaN
4.0   DNgY1uss7Q7LkSewUXWiRhwBFk5N84aF71  5.443868e+09  Exchange
5.0   DDTtqnuZ5kfRT5qh2c7sNtqrJmV3iXYdGG  5.031002e+09  Exchange
6.0   DH5yaieqoZN36fDVciNyRueRGvGLR3mr7L  2.532572e+09  Exchange
7.0   DGottmgfevJzhhfmvGdA2JpMjMJ1DsSKjJ  2.381616e+09  Exchange
8.0   DDogepartyxxxxxxxxxxxxxxxxxxw1dfzr  1.854584e+09       NaN
9.0   DGmzv39riELTuigZCUD6sWoHEHPdSbxdUB  1.400000e+09  Exchange
10.0  DHQsfy66JsYSnwjCABFN6NNqW4kHQe63oU  1.332377e+09       NaN
11.0  DTXwWCTpM6pP7NtqquiMdBE385AuW1desV  1.270010e+09       NaN
12.0  D9a1Ah7mUNAJwNqHPER4DN9zNLoqcYFDZW  1.000010e+09       NaN

In [7]:
dfD.to_csv("Data/2. Cleaned/FinalDOGE.csv")

## <u> ETH</u>
- https://etherscan.io/accounts

In [8]:
current_supply_ETH = 121516840.8

dfE = pd.read_csv("Data/1. Raw/F100ETH.csv", sep=';', index_col=0, encoding = "ISO-8859-1")
dfE = dfE.drop("BAL", axis=1)
dfE = dfE.drop("B", axis=1)
dfE = dfE.drop("Name Tag", axis=1)
dfE['Balance'] = dfE['Balance'].str.replace('Â','').str.replace('\xa0','').astype('float')

In [9]:
dfE.head(12)

                                            Address       Balance     Label
ï»¿Rank
1        0x00000000219ab540356cbb839cbe05303d7705fa  1.302281e+07       NaN
2        0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2  4.682719e+06       NaN
3        0xda9dfa130df4de4673b89022ee50ff26f6ea73cf  2.113030e+06  Exchange
4        0xbe0eb53f46cd790cd13851d5eff43d12404d33e8  1.996008e+06  Exchange
5        0x73bceb1cd57c711feac4224d062b0f6ff338501e  1.944286e+06       NaN
6        0x9bf4001d307dfd62b26a2f1307ee0c0307632d59  1.490000e+06       NaN
7        0x742d35cc6634c0532925a3b844bc454e4438f44e  1.271480e+06  Exchange
8        0x07ee55aa48bb72dcc6e9d78256648910de513eca  7.739953e+05  Exchange
9        0xf977814e90da44bfa03b6295a0616a897441acec  6.784208e+05  Exchange
10       0x011b6e24ffb0b5f5fcc564cf4183c5bbbc96d515  6.623023e+05       NaN
11       0x28c6c06298d514db089934071355e5743bf21d60  5.357589e+05  Exchange
12       0xa7efae728d2936e78bda97dc267687568dd593f3  5.234429e+05  Exchange

In [10]:
dfE.to_csv("Data/2. Cleaned/FinalETH.csv")